from abc import ABC, abstractmethod
from pathlib import Path
from typing import Dict, Any, List


class BaseDeployer(ABC):
    """Abstract base class for deployment orchestrators."""

    @abstractmethod
    def deploy(self, config: Dict[str, Any], generated_files: List[Path]) -> bool:
        """
        Deploy application using generated configuration files.

        Args:
            config: Merged configuration dictionary
            generated_files: List of file paths generated by the generator

        Returns:
            True if deployment succeeded, False otherwise
        """
        pass
