"""add gallery status and published_at

Revision ID: 9956fd4172ea
Revises: fbf2847a5a6d
Create Date: 2026-05-05 22:00:41.076766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9956fd4172ea'
down_revision: Union[str, None] = 'fbf2847a5a6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type
    gallerystatus = sa.Enum('DRAFT', 'PUBLISHED', name='gallerystatus')
    gallerystatus.create(op.get_bind(), checkfirst=True)

    # Add columns with server default for status
    op.add_column('gallery_items', sa.Column('status', gallerystatus, nullable=False, server_default='DRAFT'))
    op.add_column('gallery_items', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_gallery_items_status'), 'gallery_items', ['status'], unique=False)
    op.drop_column('gallery_items', 'is_visible')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gallery_items', sa.Column('is_visible', sa.BOOLEAN(), autoincrement=False, nullable=False, server_default=sa.text('true')))
    op.drop_index(op.f('ix_gallery_items_status'), table_name='gallery_items')
    op.drop_column('gallery_items', 'published_at')
    op.drop_column('gallery_items', 'status')

    # Drop the enum type
    sa.Enum('DRAFT', 'PUBLISHED', name='gallerystatus').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
