"""add_visitor_tracking

Revision ID: b92623584324
Revises: 9956fd4172ea
Create Date: 2026-05-06 10:46:45.093581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b92623584324'
down_revision: Union[str, None] = '9956fd4172ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visitor_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.String(length=20), nullable=True),
    sa.Column('longitude', sa.String(length=20), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('isp', sa.String(length=200), nullable=True),
    sa.Column('path', sa.String(length=500), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('referer', sa.Text(), nullable=True),
    sa.Column('is_bot', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visitor_logs_country'), 'visitor_logs', ['country'], unique=False)
    op.create_index(op.f('ix_visitor_logs_country_code'), 'visitor_logs', ['country_code'], unique=False)
    op.create_index(op.f('ix_visitor_logs_created_at'), 'visitor_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_visitor_logs_id'), 'visitor_logs', ['id'], unique=False)
    op.create_index(op.f('ix_visitor_logs_ip_address'), 'visitor_logs', ['ip_address'], unique=False)
    op.create_index(op.f('ix_visitor_logs_is_bot'), 'visitor_logs', ['is_bot'], unique=False)
    op.create_index(op.f('ix_visitor_logs_path'), 'visitor_logs', ['path'], unique=False)
    op.create_index(op.f('ix_visitor_logs_region'), 'visitor_logs', ['region'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visitor_logs_region'), table_name='visitor_logs')
    op.drop_index(op.f('ix_visitor_logs_path'), table_name='visitor_logs')
    op.drop_index(op.f('ix_visitor_logs_is_bot'), table_name='visitor_logs')
    op.drop_index(op.f('ix_visitor_logs_ip_address'), table_name='visitor_logs')
    op.drop_index(op.f('ix_visitor_logs_id'), table_name='visitor_logs')
    op.drop_index(op.f('ix_visitor_logs_created_at'), table_name='visitor_logs')
    op.drop_index(op.f('ix_visitor_logs_country_code'), table_name='visitor_logs')
    op.drop_index(op.f('ix_visitor_logs_country'), table_name='visitor_logs')
    op.drop_table('visitor_logs')
    # ### end Alembic commands ###
