"""add gallery tables

Revision ID: fbf2847a5a6d
Revises: 003
Create Date: 2026-05-05 21:30:38.349436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbf2847a5a6d'
down_revision: Union[str, None] = '003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gallery_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('caption', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('alt_text', sa.String(length=200), nullable=True),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gallery_items_filename'), 'gallery_items', ['filename'], unique=True)
    op.create_index(op.f('ix_gallery_items_id'), 'gallery_items', ['id'], unique=False)
    op.create_table('gallery_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gallery_tags_id'), 'gallery_tags', ['id'], unique=False)
    op.create_index(op.f('ix_gallery_tags_name'), 'gallery_tags', ['name'], unique=True)
    op.create_index(op.f('ix_gallery_tags_slug'), 'gallery_tags', ['slug'], unique=True)
    op.create_table('gallery_item_tags',
    sa.Column('gallery_item_id', sa.Integer(), nullable=False),
    sa.Column('gallery_tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gallery_item_id'], ['gallery_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gallery_tag_id'], ['gallery_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('gallery_item_id', 'gallery_tag_id')
    )
    op.create_index(op.f('ix_contact_messages_id'), 'contact_messages', ['id'], unique=False)
    op.drop_index('ix_coursework_category', table_name='coursework')
    op.drop_index('ix_coursework_institution', table_name='coursework')
    op.create_index(op.f('ix_education_id'), 'education', ['id'], unique=False)
    op.create_index(op.f('ix_experiences_id'), 'experiences', ['id'], unique=False)
    op.create_index(op.f('ix_profile_links_id'), 'profile_links', ['id'], unique=False)
    op.create_index(op.f('ix_publications_id'), 'publications', ['id'], unique=False)
    op.create_index(op.f('ix_skills_id'), 'skills', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skills_id'), table_name='skills')
    op.drop_index(op.f('ix_publications_id'), table_name='publications')
    op.drop_index(op.f('ix_profile_links_id'), table_name='profile_links')
    op.drop_index(op.f('ix_experiences_id'), table_name='experiences')
    op.drop_index(op.f('ix_education_id'), table_name='education')
    op.create_index('ix_coursework_institution', 'coursework', ['institution'], unique=False)
    op.create_index('ix_coursework_category', 'coursework', ['category'], unique=False)
    op.drop_index(op.f('ix_contact_messages_id'), table_name='contact_messages')
    op.drop_table('gallery_item_tags')
    op.drop_index(op.f('ix_gallery_tags_slug'), table_name='gallery_tags')
    op.drop_index(op.f('ix_gallery_tags_name'), table_name='gallery_tags')
    op.drop_index(op.f('ix_gallery_tags_id'), table_name='gallery_tags')
    op.drop_table('gallery_tags')
    op.drop_index(op.f('ix_gallery_items_id'), table_name='gallery_items')
    op.drop_index(op.f('ix_gallery_items_filename'), table_name='gallery_items')
    op.drop_table('gallery_items')
    # ### end Alembic commands ###
