from pathlib import Path
from typing import Dict, Any, List
from datetime import datetime
from jinja2 import Template
from .base import BaseGenerator


class CloudRunGenerator(BaseGenerator):
    """Generates Cloud Run deployment configurations."""

    def generate(self, config: Dict[str, Any]) -> List[Path]:
        """
        Generate Cloud Run deployment files.

        Returns:
            List of generated file paths
        """
        generated = []

        # Merge shared and target config
        target_config = self._merge_config(config, 'cloudrun')

        # Add generation timestamp
        target_config['_generated_at'] = datetime.now().isoformat()

        # Generate backend Dockerfile
        backend_dockerfile = self._generate_backend_dockerfile(target_config)
        generated.append(backend_dockerfile)

        # Generate frontend Dockerfile
        frontend_dockerfile = self._generate_frontend_dockerfile(target_config)
        generated.append(frontend_dockerfile)

        # Generate backend Cloud Run service YAML
        backend_yaml = self._generate_backend_yaml(target_config)
        generated.append(backend_yaml)

        # Generate frontend Cloud Run service YAML
        frontend_yaml = self._generate_frontend_yaml(target_config)
        generated.append(frontend_yaml)

        # Generate .env file for local testing
        env_file = self._generate_env_file(target_config)
        generated.append(env_file)

        # Generate deployment guide
        guide = self._generate_deployment_guide(target_config)
        generated.append(guide)

        return generated

    def _generate_backend_dockerfile(self, config: Dict) -> Path:
        """Generate optimized Dockerfile for backend service."""
        template_path = self.templates_dir / "cloudrun-backend.dockerfile.j2"

        if template_path.exists():
            with open(template_path) as f:
                template = Template(f.read())
            content = template.render(config=config)
        else:
            # Fallback to inline template
            content = f"""# Generated by deployment.py - DO NOT EDIT MANUALLY
# Cloud Run Backend Dockerfile
# Generated at: {config.get('_generated_at', 'timestamp')}

FROM python:3.12-slim

# Set working directory
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \\
    curl \\
    && rm -rf /var/lib/apt/lists/*

# Copy requirements first for layer caching
COPY requirements.txt .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY . .

# Create uploads directory
RUN mkdir -p /app/uploads

# Expose port (Cloud Run expects PORT env var)
ENV PORT=8080
EXPOSE 8080

# Health check
HEALTHCHECK --interval=30s --timeout=10s --start-period=40s --retries=3 \\
    CMD curl -f http://localhost:8080/health || exit 1

# Run uvicorn with environment-based configuration
CMD uvicorn app.main:app --host 0.0.0.0 --port $PORT --workers 2
"""

        output_path = self.output_dir / "backend.Dockerfile"
        with open(output_path, 'w') as f:
            f.write(content)

        return output_path

    def _generate_frontend_dockerfile(self, config: Dict) -> Path:
        """Generate optimized multi-stage Dockerfile for frontend service."""
        template_path = self.templates_dir / "cloudrun-frontend.dockerfile.j2"

        if template_path.exists():
            with open(template_path) as f:
                template = Template(f.read())
            content = template.render(config=config)
        else:
            # Fallback to inline template
            content = f"""# Generated by deployment.py - DO NOT EDIT MANUALLY
# Cloud Run Frontend Dockerfile (Multi-stage)
# Generated at: {config.get('_generated_at', 'timestamp')}

# Stage 1: Dependencies
FROM node:20-alpine AS deps
WORKDIR /app

# Copy package files
COPY package.json package-lock.json* ./
RUN npm ci --only=production

# Stage 2: Builder
FROM node:20-alpine AS builder
WORKDIR /app

# Copy dependencies from deps stage
COPY --from=deps /app/node_modules ./node_modules

# Copy application code
COPY . .

# Set build-time environment variables
ENV NEXT_TELEMETRY_DISABLED=1
ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_SITE_URL
ARG NEXT_PUBLIC_SENTRY_DSN
ARG NEXT_PUBLIC_GA_ID
ARG NEXT_PUBLIC_PLAUSIBLE_DOMAIN

ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL
ENV NEXT_PUBLIC_SENTRY_DSN=$NEXT_PUBLIC_SENTRY_DSN
ENV NEXT_PUBLIC_GA_ID=$NEXT_PUBLIC_GA_ID
ENV NEXT_PUBLIC_PLAUSIBLE_DOMAIN=$NEXT_PUBLIC_PLAUSIBLE_DOMAIN

# Build Next.js application
RUN npm run build

# Stage 3: Runner
FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=8080

# Create non-root user
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# Copy built application
COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

# Switch to non-root user
USER nextjs

EXPOSE 8080

# Health check
HEALTHCHECK --interval=30s --timeout=10s --start-period=40s --retries=3 \\
    CMD wget --no-verbose --tries=1 --spider http://localhost:8080/ || exit 1

# Start Next.js server
CMD ["node", "server.js"]
"""

        output_path = self.output_dir / "frontend.Dockerfile"
        with open(output_path, 'w') as f:
            f.write(content)

        return output_path

    def _generate_backend_yaml(self, config: Dict) -> Path:
        """Generate Cloud Run service configuration for backend."""
        template_path = self.templates_dir / "cloudrun-backend.yaml.j2"

        if template_path.exists():
            with open(template_path) as f:
                template = Template(f.read())
            content = template.render(config=config)
        else:
            # Fallback to inline template
            gcp_project = config.get('GCP_PROJECT_ID', 'your-project-id')
            region = config.get('GCP_REGION', 'us-central1')

            content = f"""# Generated by deployment.py - DO NOT EDIT MANUALLY
# Cloud Run Backend Service Configuration
# Generated at: {config.get('_generated_at', 'timestamp')}

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: portfolio-backend
  labels:
    cloud.googleapis.com/location: {region}
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '1'
        autoscaling.knative.dev/maxScale: '10'
        run.googleapis.com/cpu-throttling: 'false'
        run.googleapis.com/execution-environment: gen2
    spec:
      serviceAccountName: cloud-run-sa@{gcp_project}.iam.gserviceaccount.com
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - image: {region}-docker.pkg.dev/{gcp_project}/portfolio/backend:latest
        ports:
        - containerPort: 8080
          name: http1
        env:
        - name: ENVIRONMENT
          value: "{config.get('ENVIRONMENT', 'production')}"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-url
              key: latest
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: secret-key
              key: latest
        - name: ALGORITHM
          value: "{config.get('ALGORITHM', 'HS256')}"
        - name: ACCESS_TOKEN_EXPIRE_MINUTES
          value: "{config.get('ACCESS_TOKEN_EXPIRE_MINUTES', '30')}"
        - name: CORS_ORIGINS
          value: "{config.get('CORS_ORIGINS', '')}"
        - name: SITE_NAME
          value: "{config.get('SITE_NAME', 'Portfolio')}"
        - name: SITE_DESCRIPTION
          value: "{config.get('SITE_DESCRIPTION', '')}"
        - name: SITE_URL
          value: "{config.get('SITE_URL', '')}"
        - name: ADMIN_EMAIL
          value: "{config.get('ADMIN_EMAIL', '')}"
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: admin-password
              key: latest
        - name: R2_ACCOUNT_ID
          value: "{config.get('R2_ACCOUNT_ID', '')}"
        - name: R2_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: r2-access-key-id
              key: latest
        - name: R2_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: r2-secret-access-key
              key: latest
        - name: R2_BUCKET_NAME
          value: "{config.get('R2_BUCKET_NAME', '')}"
        - name: R2_PUBLIC_URL
          value: "{config.get('R2_PUBLIC_URL', '')}"
        - name: SENTRY_DSN
          value: "{config.get('SENTRY_DSN', '')}"
        - name: SENTRY_ENVIRONMENT
          value: "{config.get('SENTRY_ENVIRONMENT', 'production')}"
        - name: RATE_LIMIT_PER_MINUTE
          value: "{config.get('RATE_LIMIT_PER_MINUTE', '60')}"
        resources:
          limits:
            cpu: '2'
            memory: 2Gi
          requests:
            cpu: '1'
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        startupProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 0
          periodSeconds: 10
          failureThreshold: 10
"""

        output_path = self.output_dir / "backend.yaml"
        with open(output_path, 'w') as f:
            f.write(content)

        return output_path

    def _generate_frontend_yaml(self, config: Dict) -> Path:
        """Generate Cloud Run service configuration for frontend."""
        template_path = self.templates_dir / "cloudrun-frontend.yaml.j2"

        if template_path.exists():
            with open(template_path) as f:
                template = Template(f.read())
            content = template.render(config=config)
        else:
            # Fallback to inline template
            gcp_project = config.get('GCP_PROJECT_ID', 'your-project-id')
            region = config.get('GCP_REGION', 'us-central1')

            content = f"""# Generated by deployment.py - DO NOT EDIT MANUALLY
# Cloud Run Frontend Service Configuration
# Generated at: {config.get('_generated_at', 'timestamp')}

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: portfolio-frontend
  labels:
    cloud.googleapis.com/location: {region}
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '1'
        autoscaling.knative.dev/maxScale: '10'
        run.googleapis.com/cpu-throttling: 'false'
        run.googleapis.com/execution-environment: gen2
    spec:
      serviceAccountName: cloud-run-sa@{gcp_project}.iam.gserviceaccount.com
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - image: {region}-docker.pkg.dev/{gcp_project}/portfolio/frontend:latest
        ports:
        - containerPort: 8080
          name: http1
        env:
        - name: NODE_ENV
          value: "production"
        - name: NEXT_PUBLIC_API_URL
          value: "{config.get('NEXT_PUBLIC_API_URL', '')}"
        - name: NEXT_PUBLIC_SITE_URL
          value: "{config.get('NEXT_PUBLIC_SITE_URL', '')}"
        - name: NEXT_PUBLIC_SENTRY_DSN
          value: "{config.get('NEXT_PUBLIC_SENTRY_DSN', '')}"
        - name: NEXT_PUBLIC_GA_ID
          value: "{config.get('NEXT_PUBLIC_GA_ID', '')}"
        - name: NEXT_PUBLIC_PLAUSIBLE_DOMAIN
          value: "{config.get('NEXT_PUBLIC_PLAUSIBLE_DOMAIN', '')}"
        resources:
          limits:
            cpu: '2'
            memory: 1Gi
          requests:
            cpu: '1'
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        startupProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 0
          periodSeconds: 10
          failureThreshold: 10
"""

        output_path = self.output_dir / "frontend.yaml"
        with open(output_path, 'w') as f:
            f.write(content)

        return output_path

    def _generate_env_file(self, config: Dict) -> Path:
        """Generate .env.cloudrun for local testing."""
        all_vars = [
            'ENVIRONMENT', 'DATABASE_URL', 'SECRET_KEY', 'ALGORITHM',
            'ACCESS_TOKEN_EXPIRE_MINUTES', 'CORS_ORIGINS', 'SITE_NAME',
            'SITE_DESCRIPTION', 'SITE_URL', 'ADMIN_EMAIL', 'ADMIN_PASSWORD',
            'R2_ACCOUNT_ID', 'R2_ACCESS_KEY_ID', 'R2_SECRET_ACCESS_KEY',
            'R2_BUCKET_NAME', 'R2_PUBLIC_URL', 'SENTRY_DSN',
            'SENTRY_ENVIRONMENT', 'RATE_LIMIT_PER_MINUTE',
            'NEXT_PUBLIC_SITE_URL', 'NEXT_PUBLIC_API_URL',
            'NEXT_PUBLIC_SENTRY_DSN', 'NEXT_PUBLIC_GA_ID',
            'NEXT_PUBLIC_PLAUSIBLE_DOMAIN', 'GCP_PROJECT_ID', 'GCP_REGION'
        ]

        lines = [
            "# Generated by deployment.py - DO NOT EDIT MANUALLY",
            f"# Environment variables for Cloud Run local testing",
            f"# Environment: {config.get('ENVIRONMENT', 'production')}",
            f"# Target: Google Cloud Run",
            "",
        ]

        for var in all_vars:
            if var in config:
                lines.append(f"{var}={config[var]}")

        output_path = self.output_dir / ".env.cloudrun"
        with open(output_path, 'w') as f:
            f.write('\n'.join(lines))

        return output_path

    def _generate_deployment_guide(self, config: Dict) -> Path:
        """Generate comprehensive deployment instructions for Cloud Run."""
        gcp_project = config.get('GCP_PROJECT_ID', 'your-project-id')
        region = config.get('GCP_REGION', 'us-central1')

        guide = f"""# Google Cloud Run Deployment Guide

## Generated Files

This directory contains generated deployment configuration for Google Cloud Run.

**DO NOT EDIT THESE FILES MANUALLY** - they are generated by deployment.py

## Files Generated

- `backend.Dockerfile` - Optimized Dockerfile for backend service
- `frontend.Dockerfile` - Multi-stage Dockerfile for frontend service
- `backend.yaml` - Cloud Run service configuration for backend
- `frontend.yaml` - Cloud Run service configuration for frontend
- `.env.cloudrun` - Environment variables for local testing

## Prerequisites

### 1. Install Google Cloud SDK

```bash
# macOS
brew install --cask google-cloud-sdk

# Linux
curl https://sdk.cloud.google.com | bash
exec -l $SHELL

# Initialize gcloud
gcloud init
```

### 2. Set Project and Region

```bash
gcloud config set project {gcp_project}
gcloud config set run/region {region}
```

### 3. Enable Required APIs

```bash
gcloud services enable run.googleapis.com
gcloud services enable cloudbuild.googleapis.com
gcloud services enable containerregistry.googleapis.com
gcloud services enable artifactregistry.googleapis.com
gcloud services enable secretmanager.googleapis.com
```

### 4. Create Artifact Registry Repository

```bash
gcloud artifacts repositories create portfolio \\
  --repository-format=docker \\
  --location={region} \\
  --description="Portfolio application containers"
```

### 5. Configure Docker for Artifact Registry

```bash
gcloud auth configure-docker {region}-docker.pkg.dev
```

## Secrets Setup

Cloud Run uses Google Secret Manager for sensitive values. Create secrets before deployment:

```bash
# Database URL
echo -n "{config.get('DATABASE_URL', 'postgresql://...')}" | \\
  gcloud secrets create database-url --data-file=-

# Secret Key
echo -n "{config.get('SECRET_KEY', 'generate-secure-key')}" | \\
  gcloud secrets create secret-key --data-file=-

# Admin Password
echo -n "{config.get('ADMIN_PASSWORD', 'secure-password')}" | \\
  gcloud secrets create admin-password --data-file=-

# R2 Access Keys
echo -n "{config.get('R2_ACCESS_KEY_ID', '')}" | \\
  gcloud secrets create r2-access-key-id --data-file=-

echo -n "{config.get('R2_SECRET_ACCESS_KEY', '')}" | \\
  gcloud secrets create r2-secret-access-key --data-file=-
```

### Grant Cloud Run Access to Secrets

```bash
# Get Cloud Run service account
PROJECT_NUMBER=$(gcloud projects describe {gcp_project} --format='value(projectNumber)')
SERVICE_ACCOUNT="${{PROJECT_NUMBER}}-compute@developer.gserviceaccount.com"

# Grant access to all secrets
for SECRET in database-url secret-key admin-password r2-access-key-id r2-secret-access-key; do
  gcloud secrets add-iam-policy-binding $SECRET \\
    --member="serviceAccount:$SERVICE_ACCOUNT" \\
    --role="roles/secretmanager.secretAccessor"
done
```

## Deployment Steps

### Method 1: Using gcloud CLI (Recommended)

#### Build and Deploy Backend

```bash
cd /home/hendrixx/Desktop/MyPortfolio

# Build container
gcloud builds submit backend/ \\
  --tag {region}-docker.pkg.dev/{gcp_project}/portfolio/backend:latest

# Deploy to Cloud Run
gcloud run deploy portfolio-backend \\
  --image {region}-docker.pkg.dev/{gcp_project}/portfolio/backend:latest \\
  --platform managed \\
  --region {region} \\
  --allow-unauthenticated \\
  --min-instances 1 \\
  --max-instances 10 \\
  --cpu 2 \\
  --memory 2Gi \\
  --set-env-vars ENVIRONMENT={config.get('ENVIRONMENT')} \\
  --set-env-vars CORS_ORIGINS={config.get('CORS_ORIGINS', '')} \\
  --set-env-vars SITE_URL={config.get('SITE_URL', '')} \\
  --set-secrets DATABASE_URL=database-url:latest \\
  --set-secrets SECRET_KEY=secret-key:latest \\
  --set-secrets ADMIN_PASSWORD=admin-password:latest \\
  --set-secrets R2_ACCESS_KEY_ID=r2-access-key-id:latest \\
  --set-secrets R2_SECRET_ACCESS_KEY=r2-secret-access-key:latest
```

#### Build and Deploy Frontend

```bash
# Build container with build args
gcloud builds submit frontend/ \\
  --tag {region}-docker.pkg.dev/{gcp_project}/portfolio/frontend:latest \\
  --substitutions _NEXT_PUBLIC_API_URL={config.get('NEXT_PUBLIC_API_URL', '')},_NEXT_PUBLIC_SITE_URL={config.get('NEXT_PUBLIC_SITE_URL', '')}

# Deploy to Cloud Run
gcloud run deploy portfolio-frontend \\
  --image {region}-docker.pkg.dev/{gcp_project}/portfolio/frontend:latest \\
  --platform managed \\
  --region {region} \\
  --allow-unauthenticated \\
  --min-instances 1 \\
  --max-instances 10 \\
  --cpu 2 \\
  --memory 1Gi \\
  --set-env-vars NODE_ENV=production \\
  --set-env-vars NEXT_PUBLIC_API_URL={config.get('NEXT_PUBLIC_API_URL', '')} \\
  --set-env-vars NEXT_PUBLIC_SITE_URL={config.get('NEXT_PUBLIC_SITE_URL', '')}
```

### Method 2: Using Generated YAML Files

```bash
# Deploy backend
gcloud run services replace generated/cloudrun/backend.yaml --region {region}

# Deploy frontend
gcloud run services replace generated/cloudrun/frontend.yaml --region {region}
```

### Method 3: Using Deployment CLI

```bash
cd /home/hendrixx/Desktop/MyPortfolio/deployment
python deployment.py deploy --target cloudrun --env {config.get('ENVIRONMENT', 'production')}
```

## Verification

### Get Service URLs

```bash
# Backend URL
gcloud run services describe portfolio-backend \\
  --platform managed \\
  --region {region} \\
  --format 'value(status.url)'

# Frontend URL
gcloud run services describe portfolio-frontend \\
  --platform managed \\
  --region {region} \\
  --format 'value(status.url)'
```

### Test Endpoints

```bash
# Backend health check
BACKEND_URL=$(gcloud run services describe portfolio-backend --region {region} --format 'value(status.url)')
curl $BACKEND_URL/health

# Backend API docs
echo "$BACKEND_URL/docs"

# Frontend
FRONTEND_URL=$(gcloud run services describe portfolio-frontend --region {region} --format 'value(status.url)')
curl -I $FRONTEND_URL
```

## Custom Domain Setup

### 1. Map Custom Domain

```bash
# Backend
gcloud run domain-mappings create \\
  --service portfolio-backend \\
  --domain api.yourdomain.com \\
  --region {region}

# Frontend
gcloud run domain-mappings create \\
  --service portfolio-frontend \\
  --domain yourdomain.com \\
  --region {region}
```

### 2. Update DNS Records

Follow instructions from:
```bash
gcloud run domain-mappings describe \\
  --domain yourdomain.com \\
  --region {region}
```

## Monitoring and Logs

### View Logs

```bash
# Backend logs
gcloud run logs read portfolio-backend --region {region} --limit 50

# Frontend logs
gcloud run logs read portfolio-frontend --region {region} --limit 50

# Follow logs (live)
gcloud run logs tail portfolio-backend --region {region}
```

### Cloud Console

- **Services:** https://console.cloud.google.com/run?project={gcp_project}
- **Logs:** https://console.cloud.google.com/logs/query?project={gcp_project}
- **Metrics:** https://console.cloud.google.com/monitoring?project={gcp_project}

## Scaling Configuration

Update autoscaling settings:

```bash
# Backend
gcloud run services update portfolio-backend \\
  --region {region} \\
  --min-instances 1 \\
  --max-instances 20 \\
  --cpu 4 \\
  --memory 4Gi \\
  --concurrency 100

# Frontend
gcloud run services update portfolio-frontend \\
  --region {region} \\
  --min-instances 1 \\
  --max-instances 20 \\
  --cpu 2 \\
  --memory 2Gi \\
  --concurrency 100
```

## Rolling Back

### Rollback to Previous Revision

```bash
# List revisions
gcloud run revisions list --service portfolio-backend --region {region}

# Rollback to specific revision
gcloud run services update-traffic portfolio-backend \\
  --to-revisions REVISION_NAME=100 \\
  --region {region}
```

## CI/CD Integration

### Cloud Build Configuration

Create `cloudbuild.yaml`:

```yaml
steps:
  # Build backend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '{region}-docker.pkg.dev/{gcp_project}/portfolio/backend:$SHORT_SHA', 'backend/']

  # Build frontend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '{region}-docker.pkg.dev/{gcp_project}/portfolio/frontend:$SHORT_SHA', 'frontend/']

  # Deploy backend
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: ['gcloud', 'run', 'deploy', 'portfolio-backend', '--image', '{region}-docker.pkg.dev/{gcp_project}/portfolio/backend:$SHORT_SHA', '--region', '{region}']

  # Deploy frontend
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: ['gcloud', 'run', 'deploy', 'portfolio-frontend', '--image', '{region}-docker.pkg.dev/{gcp_project}/portfolio/frontend:$SHORT_SHA', '--region', '{region}']

images:
  - '{region}-docker.pkg.dev/{gcp_project}/portfolio/backend:$SHORT_SHA'
  - '{region}-docker.pkg.dev/{gcp_project}/portfolio/frontend:$SHORT_SHA'
```

### Create Build Trigger

```bash
gcloud builds triggers create github \\
  --repo-name=MyPortfolio \\
  --repo-owner=your-github-username \\
  --branch-pattern="^main$" \\
  --build-config=cloudbuild.yaml
```

## Cost Optimization

1. **Set appropriate min-instances:** Use 0 for dev/staging, 1+ for production
2. **Adjust CPU allocation:** Use CPU throttling for cost savings when traffic is low
3. **Configure timeout:** Set shorter timeout for faster failure detection
4. **Use Cloud CDN:** Enable CDN for frontend to reduce Cloud Run requests

## Troubleshooting

### Service Won't Start

```bash
# Check logs for errors
gcloud run logs read portfolio-backend --region {region} --limit 100

# Check service status
gcloud run services describe portfolio-backend --region {region}
```

### Secret Access Issues

```bash
# Verify secret exists
gcloud secrets describe database-url

# Check IAM permissions
gcloud secrets get-iam-policy database-url
```

### Build Failures

```bash
# View build logs
gcloud builds list --limit 5
gcloud builds log BUILD_ID
```

### Connection Issues

```bash
# Test from Cloud Shell
curl -v https://portfolio-backend-xxx-uc.a.run.app/health

# Check VPC configuration if using private services
gcloud run services describe portfolio-backend --region {region} --format 'value(spec.template.spec.containers[0].resources)'
```

## Cleanup

### Delete Services

```bash
gcloud run services delete portfolio-backend --region {region}
gcloud run services delete portfolio-frontend --region {region}
```

### Delete Container Images

```bash
gcloud artifacts docker images list {region}-docker.pkg.dev/{gcp_project}/portfolio
gcloud artifacts docker images delete {region}-docker.pkg.dev/{gcp_project}/portfolio/backend:latest
gcloud artifacts docker images delete {region}-docker.pkg.dev/{gcp_project}/portfolio/frontend:latest
```

### Delete Secrets

```bash
gcloud secrets delete database-url
gcloud secrets delete secret-key
gcloud secrets delete admin-password
gcloud secrets delete r2-access-key-id
gcloud secrets delete r2-secret-access-key
```

---

Generated: {config.get('_generated_at', 'timestamp')}
Command: deployment.py generate --target cloudrun --env {config.get('ENVIRONMENT', 'production')}

## Additional Resources

- [Cloud Run Documentation](https://cloud.google.com/run/docs)
- [Cloud Run Pricing](https://cloud.google.com/run/pricing)
- [Secret Manager Documentation](https://cloud.google.com/secret-manager/docs)
- [Artifact Registry Documentation](https://cloud.google.com/artifact-registry/docs)
"""

        output_path = self.output_dir / "DEPLOYMENT.md"
        with open(output_path, 'w') as f:
            f.write(guide)

        return output_path
