from pathlib import Path
from typing import Dict, Any, List
from datetime import datetime
from jinja2 import Template
from .base import BaseGenerator


class DockerGenerator(BaseGenerator):
    """Generates Docker Compose deployment configurations."""

    def generate(self, config: Dict[str, Any]) -> List[Path]:
        """
        Generate Docker Compose deployment files.

        Returns:
            List of generated file paths
        """
        generated = []

        # Merge shared and target config
        target_config = self._merge_config(config, 'docker')

        # Add generation timestamp
        target_config['_generated_at'] = datetime.now().isoformat()

        # Generate docker-compose.yml
        docker_compose = self._generate_docker_compose_yml(target_config)
        generated.append(docker_compose)

        # Generate .env files
        shared_env = self._generate_shared_env(target_config)
        backend_env = self._generate_backend_env(target_config)
        frontend_env = self._generate_frontend_env(target_config)
        generated.extend([shared_env, backend_env, frontend_env])

        # Generate deployment guide
        guide = self._generate_deployment_guide(target_config)
        generated.append(guide)

        return generated

    def _generate_docker_compose_yml(self, config: Dict) -> Path:
        """Generate docker-compose.yml from template."""
        template_path = self.templates_dir / "docker-compose.yml.j2"

        with open(template_path) as f:
            template = Template(f.read())

        content = template.render(config=config)

        output_path = self.output_dir / "docker-compose.yml"
        with open(output_path, 'w') as f:
            f.write(content)

        return output_path

    def _generate_shared_env(self, config: Dict) -> Path:
        """Generate shared .env file for docker-compose."""
        shared_vars = [
            'ENVIRONMENT', 'DB_USER', 'DB_PASSWORD', 'DB_NAME',
            'REDIS_PASSWORD'
        ]

        lines = [
            "# Generated by deployment.py - DO NOT EDIT MANUALLY",
            f"# Shared environment variables for Docker Compose",
            f"# Environment: {config.get('ENVIRONMENT', 'production')}",
            "",
        ]

        for var in shared_vars:
            if var in config:
                lines.append(f"{var}={config[var]}")

        output_path = self.output_dir / ".env"
        with open(output_path, 'w') as f:
            f.write('\n'.join(lines))

        return output_path

    def _generate_backend_env(self, config: Dict) -> Path:
        """Generate backend/.env file for Docker."""
        backend_vars = [
            'ENVIRONMENT', 'SECRET_KEY', 'ALGORITHM',
            'ACCESS_TOKEN_EXPIRE_MINUTES', 'CORS_ORIGINS',
            'SITE_NAME', 'SITE_DESCRIPTION', 'SITE_URL',
            'ADMIN_EMAIL', 'ADMIN_PASSWORD',
            'DB_HOST', 'DB_PORT', 'DB_USER', 'DB_PASSWORD', 'DB_NAME',
            'REDIS_HOST', 'REDIS_PORT', 'REDIS_PASSWORD',
            'R2_ACCOUNT_ID', 'R2_ACCESS_KEY_ID', 'R2_SECRET_ACCESS_KEY',
            'R2_BUCKET_NAME', 'R2_PUBLIC_URL',
            'SENTRY_DSN', 'SENTRY_ENVIRONMENT', 'SENTRY_TRACES_SAMPLE_RATE',
            'SENTRY_PROFILES_SAMPLE_RATE', 'RATE_LIMIT_PER_MINUTE',
            'MAX_UPLOAD_SIZE'
        ]

        lines = [
            "# Generated by deployment.py - DO NOT EDIT MANUALLY",
            f"# Backend environment variables for Docker",
            f"# Environment: {config.get('ENVIRONMENT', 'production')}",
            f"# Target: Docker",
            "",
        ]

        # Build DATABASE_URL from components
        if all(k in config for k in ['DB_USER', 'DB_PASSWORD', 'DB_HOST', 'DB_PORT', 'DB_NAME']):
            db_url = f"postgresql://{config['DB_USER']}:{config['DB_PASSWORD']}@{config['DB_HOST']}:{config['DB_PORT']}/{config['DB_NAME']}"
            lines.append(f"DATABASE_URL={db_url}")
            lines.append("")

        # Build REDIS_URL from components
        if all(k in config for k in ['REDIS_HOST', 'REDIS_PORT', 'REDIS_PASSWORD']):
            redis_url = f"redis://:{config['REDIS_PASSWORD']}@{config['REDIS_HOST']}:{config['REDIS_PORT']}/0"
            lines.append(f"REDIS_URL={redis_url}")
            lines.append("")

        for var in backend_vars:
            if var in config:
                lines.append(f"{var}={config[var]}")

        output_path = self.output_dir / "backend" / ".env"
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, 'w') as f:
            f.write('\n'.join(lines))

        return output_path

    def _generate_frontend_env(self, config: Dict) -> Path:
        """Generate frontend/.env.production file for Docker."""
        frontend_vars = [
            'NEXT_PUBLIC_SITE_URL', 'NEXT_PUBLIC_API_URL',
            'NEXT_PUBLIC_SENTRY_DSN', 'NEXT_PUBLIC_GA_ID',
            'NEXT_PUBLIC_PLAUSIBLE_DOMAIN'
        ]

        lines = [
            "# Generated by deployment.py - DO NOT EDIT MANUALLY",
            f"# Frontend environment variables for Docker",
            f"# Environment: {config.get('ENVIRONMENT', 'production')}",
            f"# Target: Docker",
            "",
            "NODE_ENV=production",
            "",
        ]

        for var in frontend_vars:
            if var in config:
                lines.append(f"{var}={config[var]}")

        output_path = self.output_dir / "frontend" / ".env.production"
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, 'w') as f:
            f.write('\n'.join(lines))

        return output_path

    def _generate_deployment_guide(self, config: Dict) -> Path:
        """Generate deployment instructions for Docker."""
        guide = f"""# Docker Compose Deployment Guide

## Generated Files

This directory contains generated deployment configuration for Docker Compose.

**DO NOT EDIT THESE FILES MANUALLY** - they are generated by deployment.py

## Files Generated

- `docker-compose.yml` - Docker Compose orchestration configuration
- `.env` - Shared environment variables (DB and Redis credentials)
- `backend/.env` - Backend service environment variables
- `frontend/.env.production` - Frontend build-time environment variables

## Prerequisites

1. **Docker and Docker Compose installed**
   ```bash
   docker --version
   docker-compose --version
   ```

2. **Backend and Frontend Dockerfiles**
   Ensure these exist:
   - `/home/hendrixx/Desktop/MyPortfolio/backend/Dockerfile`
   - `/home/hendrixx/Desktop/MyPortfolio/frontend/Dockerfile`

## Deployment Steps

### 1. Copy Generated Files to Project

```bash
# From deployment directory
cd /home/hendrixx/Desktop/MyPortfolio/deployment

# Copy docker-compose.yml to project root
cp generated/docker/docker-compose.yml /home/hendrixx/Desktop/MyPortfolio/

# Copy environment files
cp generated/docker/.env /home/hendrixx/Desktop/MyPortfolio/
cp generated/docker/backend/.env /home/hendrixx/Desktop/MyPortfolio/backend/
cp generated/docker/frontend/.env.production /home/hendrixx/Desktop/MyPortfolio/frontend/
```

### 2. Start Services

```bash
cd /home/hendrixx/Desktop/MyPortfolio

# Start all services in detached mode
docker-compose up -d

# View logs
docker-compose logs -f

# View specific service logs
docker-compose logs -f backend
docker-compose logs -f frontend
```

### 3. Initialize Database

```bash
# Run database migrations
docker-compose exec backend alembic upgrade head

# Create admin user (if needed)
docker-compose exec backend python -m scripts.create_admin
```

### 4. Verify Services

Check all services are healthy:

```bash
docker-compose ps
```

Expected output:
```
NAME                 STATUS              PORTS
portfolio_backend    Up (healthy)        0.0.0.0:8000->8000/tcp
portfolio_db         Up (healthy)        5432/tcp
portfolio_frontend   Up (healthy)        0.0.0.0:3000->3000/tcp
redis               Up (healthy)        6379/tcp
```

Test endpoints:
- **Frontend:** http://localhost:3000
- **Backend API:** http://localhost:8000/api/health
- **Backend Docs:** http://localhost:8000/docs

## Configuration

### Database Connection

- **Host:** portfolio_db (container name)
- **Port:** {config.get('DB_PORT', 5432)}
- **User:** {config.get('DB_USER', 'postgres')}
- **Database:** {config.get('DB_NAME', 'portfolio')}

### Redis Connection

- **Host:** redis (container name)
- **Port:** {config.get('REDIS_PORT', 6379)}
- **Password:** (set in .env)

### Networking

All services are connected via the `portfolio_network` bridge network.

## Management Commands

### Stop Services
```bash
docker-compose down
```

### Stop and Remove Volumes
```bash
docker-compose down -v
```

### Restart a Service
```bash
docker-compose restart backend
docker-compose restart frontend
```

### Rebuild a Service
```bash
docker-compose up -d --build backend
docker-compose up -d --build frontend
```

### View Service Status
```bash
docker-compose ps
docker-compose top
```

### Access Service Shell
```bash
docker-compose exec backend bash
docker-compose exec frontend sh
docker-compose exec portfolio_db psql -U {config.get('DB_USER', 'postgres')} -d {config.get('DB_NAME', 'portfolio')}
```

### Backup Database
```bash
docker-compose exec -T portfolio_db pg_dump -U {config.get('DB_USER', 'postgres')} {config.get('DB_NAME', 'portfolio')} > backup_$(date +%Y%m%d_%H%M%S).sql
```

### Restore Database
```bash
docker-compose exec -T portfolio_db psql -U {config.get('DB_USER', 'postgres')} {config.get('DB_NAME', 'portfolio')} < backup.sql
```

## Volumes

Persistent data is stored in Docker volumes:

- `postgres_data` - PostgreSQL database files
- `redis_data` - Redis persistence files
- `backend_uploads` - Uploaded files (images, documents)

View volumes:
```bash
docker volume ls | grep portfolio
```

## Production Deployment

For production, consider:

1. **Reverse Proxy:** Use nginx or Traefik in front of services
2. **SSL/TLS:** Configure HTTPS with Let's Encrypt
3. **Resource Limits:** Add memory and CPU limits to services
4. **Monitoring:** Add Prometheus + Grafana or similar
5. **Backups:** Automate database and volume backups
6. **Secrets:** Use Docker secrets or external secret management
7. **Logging:** Configure centralized logging (ELK, Loki)

## Troubleshooting

### Service Won't Start

```bash
# Check logs
docker-compose logs backend

# Check if ports are already in use
sudo netstat -tulpn | grep -E '3000|8000'
```

### Database Connection Fails

```bash
# Check database is healthy
docker-compose ps portfolio_db

# Check connection from backend
docker-compose exec backend nc -zv portfolio_db 5432
```

### Frontend Can't Reach Backend

Ensure `NEXT_PUBLIC_API_URL` is correctly set:
- For external access: `https://api.ldj.heistats.com`
- For internal Docker network: Use service name `http://backend:8000`

### Clear Everything and Start Fresh

```bash
docker-compose down -v
docker-compose up -d --build
```

## Using the Deployment CLI

You can also deploy using the deployment script:

```bash
cd /home/hendrixx/Desktop/MyPortfolio/deployment
python deployment.py deploy --target docker --env {config.get('ENVIRONMENT', 'production')}
```

---

Generated: {config.get('_generated_at', 'timestamp')}
Command: deployment.py generate --target docker --env {config.get('ENVIRONMENT', 'production')}
"""

        output_path = self.output_dir / "DEPLOYMENT.md"
        with open(output_path, 'w') as f:
            f.write(guide)

        return output_path
