from pathlib import Path
from typing import Dict, Any, List
from datetime import datetime
from jinja2 import Template
from .base import BaseGenerator


class VercelGenerator(BaseGenerator):
    """Generates Vercel deployment configurations."""

    def generate(self, config: Dict[str, Any]) -> List[Path]:
        """
        Generate Vercel deployment files.

        Returns:
            List of generated file paths
        """
        generated = []

        # Merge shared and target config
        target_config = self._merge_config(config, 'vercel')

        # Add generation timestamp
        target_config['_generated_at'] = datetime.now().isoformat()

        # Generate vercel.json
        vercel_json = self._generate_vercel_json(target_config)
        generated.append(vercel_json)

        # Generate .env files
        backend_env = self._generate_backend_env(target_config)
        frontend_env = self._generate_frontend_env(target_config)
        generated.extend([backend_env, frontend_env])

        # Generate deployment guide
        guide = self._generate_deployment_guide(target_config)
        generated.append(guide)

        return generated

    def _generate_vercel_json(self, config: Dict) -> Path:
        """Generate vercel.json from template."""
        template_path = self.templates_dir / "vercel.json.j2"

        with open(template_path) as f:
            template = Template(f.read())

        content = template.render(config=config)

        output_path = self.output_dir / "vercel.json"
        with open(output_path, 'w') as f:
            f.write(content)

        return output_path

    def _generate_backend_env(self, config: Dict) -> Path:
        """Generate backend .env file."""
        backend_vars = [
            'ENVIRONMENT', 'DATABASE_URL', 'SECRET_KEY', 'ALGORITHM',
            'ACCESS_TOKEN_EXPIRE_MINUTES', 'CORS_ORIGINS', 'SITE_NAME',
            'SITE_DESCRIPTION', 'SITE_URL', 'ADMIN_EMAIL', 'ADMIN_PASSWORD',
            'R2_ACCOUNT_ID', 'R2_ACCESS_KEY_ID', 'R2_SECRET_ACCESS_KEY',
            'R2_BUCKET_NAME', 'R2_PUBLIC_URL', 'SENTRY_DSN',
            'SENTRY_ENVIRONMENT', 'RATE_LIMIT_PER_MINUTE'
        ]

        lines = [
            "# Generated by deployment.py - DO NOT EDIT MANUALLY",
            f"# Environment: {config.get('ENVIRONMENT', 'production')}",
            f"# Target: Vercel",
            "",
        ]

        for var in backend_vars:
            if var in config:
                lines.append(f"{var}={config[var]}")

        output_path = self.output_dir / ".env.backend"
        with open(output_path, 'w') as f:
            f.write('\n'.join(lines))

        return output_path

    def _generate_frontend_env(self, config: Dict) -> Path:
        """Generate frontend .env file."""
        frontend_vars = [
            'NEXT_PUBLIC_SITE_URL', 'NEXT_PUBLIC_API_URL',
            'NEXT_PUBLIC_SENTRY_DSN', 'NEXT_PUBLIC_GA_ID',
            'NEXT_PUBLIC_PLAUSIBLE_DOMAIN'
        ]

        lines = [
            "# Generated by deployment.py - DO NOT EDIT MANUALLY",
            f"# Environment: {config.get('ENVIRONMENT', 'production')}",
            f"# Target: Vercel",
            "",
        ]

        for var in frontend_vars:
            if var in config:
                lines.append(f"{var}={config[var]}")

        output_path = self.output_dir / ".env.frontend"
        with open(output_path, 'w') as f:
            f.write('\n'.join(lines))

        return output_path

    def _generate_deployment_guide(self, config: Dict) -> Path:
        """Generate deployment instructions."""
        guide = f"""# Vercel Deployment Guide

## Generated Files

This directory contains generated deployment configuration for Vercel.

**DO NOT EDIT THESE FILES MANUALLY** - they are generated by deployment.py

## Files Generated

- `vercel.json` - Vercel project configuration
- `.env.backend` - Backend environment variables (for API functions)
- `.env.frontend` - Frontend environment variables (for Next.js build)

## Deployment Steps

### 1. Set Environment Variables in Vercel Dashboard

Go to: https://vercel.com/your-team/your-project/settings/environment-variables

Add the following variables for **Production**:

```bash
# From .env.backend
ENVIRONMENT={config.get('ENVIRONMENT')}
DATABASE_URL={config.get('DATABASE_URL', '<from-neon-dashboard>')}
SECRET_KEY={config.get('SECRET_KEY', '<generate-secure-key>')}
CORS_ORIGINS={config.get('CORS_ORIGINS')}
SITE_URL={config.get('SITE_URL')}
ADMIN_EMAIL={config.get('ADMIN_EMAIL')}
ADMIN_PASSWORD={config.get('ADMIN_PASSWORD', '<secure-password>')}

# R2 Storage
R2_ACCOUNT_ID={config.get('R2_ACCOUNT_ID')}
R2_ACCESS_KEY_ID={config.get('R2_ACCESS_KEY_ID')}
R2_SECRET_ACCESS_KEY={config.get('R2_SECRET_ACCESS_KEY')}
R2_BUCKET_NAME={config.get('R2_BUCKET_NAME')}
R2_PUBLIC_URL={config.get('R2_PUBLIC_URL')}

# Frontend
NEXT_PUBLIC_SITE_URL={config.get('NEXT_PUBLIC_SITE_URL')}
NEXT_PUBLIC_API_URL={config.get('NEXT_PUBLIC_API_URL', '')}

# Optional
SENTRY_DSN={config.get('SENTRY_DSN', '')}
```

### 2. Copy vercel.json to Project Root

```bash
cp generated/vercel/vercel.json /home/hendrixx/Desktop/MyPortfolio/vercel.json
```

### 3. Deploy

```bash
cd /home/hendrixx/Desktop/MyPortfolio
vercel --prod
```

Or use the deployment CLI:

```bash
python deployment.py deploy --target vercel --env production
```

## Verification

After deployment, verify:

1. **Frontend loads:** {config.get('SITE_URL')}
2. **API responds:** {config.get('SITE_URL')}/api/health
3. **No localhost in responses:** Check sitemap, robots.txt
4. **File uploads work:** Test admin gallery upload

## Rollback

If deployment fails, rollback in Vercel dashboard or:

```bash
vercel rollback
```

---

Generated: {config.get('_generated_at', 'timestamp')}
Command: deployment.py generate --target vercel --env production
"""

        output_path = self.output_dir / "DEPLOYMENT.md"
        with open(output_path, 'w') as f:
            f.write(guide)

        return output_path
